use ggez::input::keyboard::{KeyCode, KeyInput, KeyMods};

pub fn to_char(key_input: &KeyInput) -> Option<char> {
    if key_input.keycode == None {
        return None;
    }
    if let Some(c) = key_code_to_char(&key_input.keycode.unwrap()) {
        if key_input.mods.contains(KeyMods::SHIFT) {
            return match c {
                '1' => Some('!'),
                '2' => Some('@'),
                '3' => Some('#'),
                '4' => Some('$'),
                '5' => Some('%'),
                '6' => Some('^'),
                '7' => Some('&'),
                '8' => Some('*'),
                '9' => Some('('),
                '0' => Some(')'),
                'a' => Some('A'),
                'b' => Some('B'),
                'c' => Some('C'),
                'd' => Some('D'),
                'e' => Some('E'),
                'f' => Some('F'),
                'g' => Some('G'),
                'h' => Some('H'),
                'i' => Some('I'),
                'j' => Some('J'),
                'k' => Some('K'),
                'l' => Some('L'),
                'm' => Some('M'),
                'n' => Some('N'),
                'o' => Some('O'),
                'p' => Some('P'),
                'q' => Some('Q'),
                'r' => Some('R'),
                's' => Some('S'),
                't' => Some('T'),
                'u' => Some('U'),
                'v' => Some('V'),
                'w' => Some('W'),
                'x' => Some('X'),
                'y' => Some('Y'),
                'z' => Some('Z'),
                '+' => Some('='),
                '-' => Some('_'),
                '/' => Some('?'),
                '.' => Some('>'),
                ',' => Some('<'),
                '[' => Some('{'),
                ']' => Some('}'),
                '\\' => Some('|'),
                ';' => Some(':'),
                '\'' => Some('\"'),
                _ => Some(c),
            };
        } else {
            return Some(c);
        }
    } else {
        return None;
    }
}

fn key_code_to_char(key_code: &KeyCode) -> Option<char> {
    match key_code {
        KeyCode::Key1 => Some('1'),
        KeyCode::Key2 => Some('2'),
        KeyCode::Key3 => Some('3'),
        KeyCode::Key4 => Some('4'),
        KeyCode::Key5 => Some('5'),
        KeyCode::Key6 => Some('6'),
        KeyCode::Key7 => Some('7'),
        KeyCode::Key8 => Some('8'),
        KeyCode::Key9 => Some('9'),
        KeyCode::Key0 => Some('0'),
        KeyCode::A => Some('a'),
        KeyCode::B => Some('b'),
        KeyCode::C => Some('c'),
        KeyCode::D => Some('d'),
        KeyCode::E => Some('e'),
        KeyCode::F => Some('f'),
        KeyCode::G => Some('g'),
        KeyCode::H => Some('h'),
        KeyCode::I => Some('i'),
        KeyCode::J => Some('j'),
        KeyCode::K => Some('k'),
        KeyCode::L => Some('l'),
        KeyCode::M => Some('m'),
        KeyCode::N => Some('n'),
        KeyCode::O => Some('o'),
        KeyCode::P => Some('p'),
        KeyCode::Q => Some('q'),
        KeyCode::R => Some('r'),
        KeyCode::S => Some('s'),
        KeyCode::T => Some('t'),
        KeyCode::U => Some('u'),
        KeyCode::V => Some('v'),
        KeyCode::W => Some('w'),
        KeyCode::X => Some('x'),
        KeyCode::Y => Some('y'),
        KeyCode::Z => Some('z'),
        //KeyCode::Back => Some('\u{0008}'),
        //KeyCode::Return => Some('\r'),
        KeyCode::Space => Some(' '),
        //KeyCode::Tab => Some('\t'),
        KeyCode::Numpad0 => Some('0'),
        KeyCode::Numpad1 => Some('1'),
        KeyCode::Numpad2 => Some('2'),
        KeyCode::Numpad3 => Some('3'),
        KeyCode::Numpad4 => Some('4'),
        KeyCode::Numpad5 => Some('5'),
        KeyCode::Numpad6 => Some('6'),
        KeyCode::Numpad7 => Some('7'),
        KeyCode::Numpad8 => Some('8'),
        KeyCode::Numpad9 => Some('9'),
        KeyCode::NumpadAdd => Some('+'),
        KeyCode::NumpadSubtract => Some('-'),
        KeyCode::NumpadMultiply => Some('*'),
        KeyCode::NumpadDivide => Some('/'),
        KeyCode::NumpadDecimal => Some('.'),
        KeyCode::NumpadComma => Some(','),
        KeyCode::NumpadEquals => Some('='),
        //KeyCode::NumpadEnter => Some('\r'),
        KeyCode::Minus => Some('-'),
        KeyCode::Plus => Some('+'),
        KeyCode::LBracket => Some('['),
        KeyCode::RBracket => Some(']'),
        KeyCode::Backslash => Some('\\'),
        KeyCode::Semicolon => Some(';'),
        KeyCode::Apostrophe => Some('\''),
        KeyCode::Grave => Some('`'),
        KeyCode::Comma => Some(','),
        KeyCode::Period => Some('.'),
        KeyCode::Slash => Some('/'),
        KeyCode::Equals => Some('='),
        KeyCode::Colon => Some(':'),
        KeyCode::Asterisk => Some('*'),
        KeyCode::At => Some('@'),
        KeyCode::Underline => Some('_'),
        KeyCode::Caret => Some('^'),
        KeyCode::Yen => Some('¥'),
        _ => None,
    }
}
